source 'https://rubygems.org'

gem 'rails', '4.1.2'
gem 'mysql2'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'therubyracer',  platforms: :ruby
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'bcrypt', '~> 3.1.7'
gem 'unicorn'
gem 'capistrano-rails', group: :development
gem 'slim-rails'
gem 'websocket-rails'
gem 'rails_config'
gem 'gon'
gem 'awesome_print'
gem 'grape'
gem 'rabl'
gem 'oj'
gem 'kaminari'
gem "bootstrap-sass", "~> 3.1.1.0"
gem 'font-awesome-sass'

group :development, :test do
  gem 'ffaker'
  gem 'json_expressions'
  gem 'spring'
  gem 'byebug'
  gem 'binding_of_caller'
  gem 'rails-clean-logs'
  gem 'colorize_unpermitted_parameters'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'database_rewinder'
end
